# Generated by Django 4.1.5 on 2023-04-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
